### ISSUE TITLE
App lock shows on clearing the app from recent apps

### ISSUE THREAD

**Issue by Satanarious** [aload0/AppLock#3]
So I locked one of my apps and then whenever I clear that app from the recent apps, the AppLock would show up and if I unlock it, the app opens again.

**Comment by PranavPurwar** [comment]
Should be fixed with the latest commits, can you check this build? https://github.com/PranavPurwar/AppLock/raw/refs/heads/master/app/release/app-release.apk

**Comment by Satanarious** [comment]
Fixed now. Thanks for the quick update.

**Comment by Satanarious** [comment]
Still happening with [this](https://github.com/PranavPurwar/AppLock/issues/2#issuecomment-2949791032) build.

**Comment by PranavPurwar** [comment]
> Still happening with [this](https://github.com/PranavPurwar/AppLock/issues/2#issuecomment-2949791032) build.

Can you try closing applock from recents then checking if it still happens?

**Comment by Satanarious** [comment]
This was not happening after I installed this build but after sometime the app lock stopped working, it won't show up when I opened a locked app. So I opened the app lock app and then it started working, but then the recent app problem started happening again. Now I've cleared the app from recents and it's not happening somehow. I donno what might be the problem here.

**Comment by Satanarious** [comment]
Seems to be fixed with [this](build).

I'll do some testing and close this issue in a day or two.

**Comment by Satanarious** [comment]
It still happens randomly. I cannot pinpoint any reproducible steps to follow to get this behaviour but this happens often to bother me and sometimes it even appears on the lockscreen when the phone is locked.

**Comment by PranavPurwar** [comment]
Yes, I also noticed it sometimes appearing on lock screen. I think its a software issue since apps shouldn't be allowed on lock screen. I'll try to find a way to check if device is locked

**Comment by Satanarious** [comment]
The lockscreen one is less bothersome then the ones that appear randomly after closing a locked app or opening any app.

**Comment by PranavPurwar** [comment]
The lock screen should be fixed with the recents issues in the new release

**Comment by Satanarious** [comment]
I checked out the new release and it seems like the problem was not at all with the recents app clearing entirely, but because the app lock would show more than one time after showing up once. So if I open a locked app then even if I unlock the app, the app lock will still show again for some reason. And it's because of that. If I opened the app and instantly cleared it, the app lock would show again. So I think the problem is entirely another issue with the app lock where it would show more than once after unlock or even if you open a locked app and don't interact with the app lock for a while. 

But if you clear the locked app from recent apps, the app lock is still showing up without even opening the app and on unlocking it is still opening the app. So the recents issue still exists.

**Comment by PranavPurwar** [comment]
> I checked out the new release and it seems like the problem was not at all with the recents app clearing entirely, but because the app lock would show more than one time after showing up once. So if I open a locked app then even if I unlock the app, the app lock will still show again for some reason. And it's because of that. If I opened the app and instantly cleared it, the app lock would show again. So I think the problem is entirely another issue with the app lock where it would show more than once after unlock or even if you open a locked app and don't interact with the app lock for a while.
> 
> But if you clear the locked app from recent apps, the app lock is still showing up without even opening the app and on unlocking it is still opening the app. So the recents issue still exists.

That issue is because some apps rely on custom splash screens. The lock screen shows up when the app is launched, but then the locked app opens up the home screen over the lock screen. There is no other way to fix this issue other than launch the lock screen over the app again. I think I added logic so that the previous screens are destroyed when a new one is launched, but i guess it isn't working properly. I'll try to find other ways to prevent that, though the lock screen would still show up again

**Comment by PranavPurwar** [comment]
Found a hack around it, it would work 94% of time but the lock screen might still show up occasionally. I'll upload a release with the fix ~~tomorrow~~ today

**Comment by PranavPurwar** [comment]
Try the solution in [v1.2](https://github.com/PranavPurwar/AppLock/releases/tag/v1.2)
