### ISSUE TITLE
Swiping always activate the locker

### ISSUE THREAD

**Issue by JonnyTech** [aload0/AppLock#32]
I use AppLock to protect WhatsApp. I regularly swipe between messages. It is much quicker and more convenient.

If I use the in-app back button to return from a message to the list then all is fine.

Swiping backwards from a message to get back to the message list will always bring up the locker password input screen and interrupts my workflow.

**Comment by Andros42** [comment]
> I use AppLock to protect WhatsApp. I regularly swipe between messages. It is much quicker and more convenient.
> 
> If I use the in-app back button to return from a message to the list then all is fine.
> 
> Swiping backwards from a message to get back to the message list will always bring up the locker password input screen and interrupts my workflow.

Then use WhatsApp's inbuilt applocker

Three dots>Settings>privacy>applocker

**Comment by JonnyTech** [comment]
> Then use WhatsApp's inbuilt applocker
> Three dots>Settings>privacy>applocker

Thanks, I found chat lock, but that seems to only lock selected chats, I want to lock the entire app.

**Comment by jeeneo** [comment]
> > Then use WhatsApp's inbuilt applocker
> > Three dots>Settings>privacy>applocker
> 
> Thanks, I found chat lock, but that seems to only lock selected chats, I want to lock the entire app.

he means here:

<img width="1080" height="1300" alt="Image" src="https://github.com/user-attachments/assets/adf68e07-1f6e-41f8-a2f6-5f0117a000fc" />

(settings > privacy > "App Lock")

which shows this when tapped:

<img width="1080" height="516" alt="Image" src="https://github.com/user-attachments/assets/8d4c569a-b471-488f-a4ad-0ea812b7739a" />

**Comment by JonnyTech** [comment]
I do not have that menu entry (latest WhatsApp on Android 13):

<img width="576" height="1280" alt="Image" src="https://github.com/user-attachments/assets/d63acb89-ed0b-465b-8b07-d189dbbaa493" />

<img width="576" height="1280" alt="Image" src="https://github.com/user-attachments/assets/afc9a19f-3256-4128-97e4-40cfdcc677d8" />

**Comment by jeeneo** [comment]
> I do not have that menu entry (latest WhatsApp on Android 13)

hmm odd, we have the same WhatsApp version, but I have Android 15

however according to their faq page on [App Locking](https://faq.whatsapp.com/1726618467788240)

<img width="1080" height="616" alt="Image" src="https://github.com/user-attachments/assets/b5bfae9d-ad43-4b33-af9d-21b812c6a01c" />

**Comment by JonnyTech** [comment]
My device does not have a fingerprint sensor or supports facial recognition so I guess that is why the option is not available. Hence why I am looking at AppLock to provide locking of the app. But the swiping issue makes it quite infuriating to use.

**Comment by PranavPurwar** [comment]
@JonnyTech I do not fully understand the problem yet. Could you provide a recording of the issue happening, along with what backend you were using (Shizuku, Usage Stats, Accessibility Service)

**Comment by PranavPurwar** [comment]
Should be fixed now on Shizuku and accessibility service, in [this build](https://github.com/PranavPurwar/AppLock/raw/refs/heads/master/app/debug/app-debug.apk)

@JonnyTech could you check?

**Comment by JonnyTech** [comment]
Sorry for not replying sooner. I was unable to made a video without revealing sensitive information. The test build did not fix the issue. In fact it was worse. With all three backends. I see that you have released v1.5.0 so I shall wait until fdroid builds it (7-10 days?) then will report back here. In the meantime, I am using another foss locker (locklock) which works correctly for me.

**Comment by PranavPurwar** [comment]
Could you try the new release?

**Comment by JonnyTech** [comment]
Thanks for the ping, I see that you have been busy with this app.

Unfortunately I cannot get the lock to function.

When opening AppLock, it asks for my pattern each time.

But WhatsApp opens without a pattern request.

![Image](https://github.com/user-attachments/assets/1a9cc380-ab49-4778-9142-aed01ab9bc48)
<br>
<img width="576" height="1280" alt="Image" src="https://github.com/user-attachments/assets/df25d394-106c-4f47-8da1-fc7b6fca6681" />
<br>
![Image](https://github.com/user-attachments/assets/2356ef17-4718-4035-9c2c-3c4a3db1a05b)
<br>
![Image](https://github.com/user-attachments/assets/ad38182f-5c5a-4203-b189-09d3798617f3)

**Comment by PranavPurwar** [comment]
> Thanks for the ping, I see that you have been busy with this app.
> 
> Unfortunately I cannot get the lock to function.
> 
> When opening AppLock, it asks for my pattern each time.
> 
> But WhatsApp opens without a pattern request.
> 
> ![Image](https://github.com/user-attachments/assets/1a9cc380-ab49-4778-9142-aed01ab9bc48) <img alt="Image" width="576" height="1280" src="https://private-user-images.githubusercontent.com/3584732/505619623-df25d394-106c-4f47-8da1-fc7b6fca6681.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjEzODg2NzcsIm5iZiI6MTc2MTM4ODM3NywicGF0aCI6Ii8zNTg0NzMyLzUwNTYxOTYyMy1kZjI1ZDM5NC0xMDZjLTRmNDctOGRhMS1mYzdiNmZjYTY2ODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMjVUMTAzMjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MzZjkwMzBiZjBiMzE1NmIwMmEyOTA1M2I0YWQ2NGNkNmE5MmFlMWI4MjI1Yjg0NmM4OTUzYzBkMDgyYWJmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TVyytQupcA6R1F1XoDR5Z6ihl3bRn5ZLcfsJYmqb1VY"> ![Image](https://github.com/user-attachments/assets/2356ef17-4718-4035-9c2c-3c4a3db1a05b) ![Image](https://github.com/user-attachments/assets/ad38182f-5c5a-4203-b189-09d3798617f3)

If you download the app through F-Droid client, it should take away the Restricted Setting message

**Comment by JonnyTech** [comment]
I did download via fdroid using the izzyondroid repo.

The main fdroid repo is stuck at version 1.3.

![Image](https://github.com/user-attachments/assets/b6efd713-56c9-431c-ad5b-2c476136e9f0)

**Comment by PranavPurwar** [comment]
> I did download via fdroid using the izzyondroid repo.
> 
> The main fdroid repo is stuck at version 1.3.
> 
> ![Image](https://github.com/user-attachments/assets/b6efd713-56c9-431c-ad5b-2c476136e9f0)

Try deleting applock, then installing it again. Some people said installing directly from fdroid clients removes the error

**Comment by JonnyTech** [comment]
> Try deleting applock, then installing it again.

That worked (also had to do https://github.com/PranavPurwar/AppLock/issues/17#issuecomment-3016575378), thanks. I can now navigate messages without constant unlock prompts.

Now I wait until someone sends me a message. There was another issue where incoming message notifications would trigger applock. It should only prompt for password when I open the app.
