### ISSUE TITLE
Lockscreen popping up repetitively after unlocking app once

### ISSUE THREAD

**Issue by Satanarious** [aload0/AppLock#37]
After a recent update, unlocking a locked app once seems to trigger a loop that causes the lock screen to pop up repeatedly, as shown in the video below. Additionally, I have checked, and this issue occurs with every locked app.

The blue semi-circle with a 'greater than' sign is an indicator for the fingerprint sensor on the power button of my phone. Just letting you know. That's when I register my fingerprint, and the app unlocks; then the lock screen appears again and asks for the fingerprint.

https://github.com/user-attachments/assets/4ee20402-e038-4cd8-a3dd-9e33f28bb621

Android: 15
Device: Motorola Razr 40 Ultra
AppLock Version: 1.4.1

**Comment by 66627392817293** [comment]
Hi, I have the same issue.

I'm using android 15 and One UI (Stock Samsung s22 Pro)

Steps to reproduce : 

1: Use AppLock set to automatically lock as soon as user leaves AND activate anti-uninstall (I didn't troubleshoot to see if that matters I just included it as it is the only parameter I changed from default config)

3: Open any app that has you opening you keyboard app at some point (Mine is Stock Samsung keyboard).

3: Go to a text field and pop up the keyboard. Write a few words and fiddle with the little blinking text bar that you can move with your thumbs. Idk what it's called sorry. Just try to do stuff with the keyboard basically. 

Expected results: App lock pops up after some time (It seems random from my POV but always happens a lot and quickly). 


Temporary solution: Set lock timeout value to any other value than instant. 

My humble opinion: The app lock thinks the user leaves the app when the keyboard flyout pops up because it thinks I opened a completely different app when in fact I haven't left the app I'm trying to type in.

Can fix pls ? :3

Thanx ^^

**Comment by Satanarious** [comment]
Mine does this for every app without any keyboard interaction.

**Comment by PranavPurwar** [comment]
@Satanarious @66627392817293 Does it happen with accessibility backend or Usage Stats?

**Comment by Satanarious** [comment]
Accessibility backend

**Comment by PranavPurwar** [comment]
Should be fixed with [this build](https://github.com/PranavPurwar/AppLock/raw/refs/heads/master/app/debug/app-debug.apk)!

**Comment by Satanarious** [comment]
The problem still persists with this build. Though it's not repetitively jumping on me like how it was doing previously but now it does that every 2-3 seconds into the app.

**Comment by NovaXi** [comment]
Same here, with the latest build (1.5)

**Comment by PranavPurwar** [comment]
> Same here, with the latest build (1.5)

Which backend were you using?

**Comment by NovaXi** [comment]
> > Same here, with the latest build (1.5)
> 
> Which backend were you using? 

Not gonna lie, I have no idea, I downloaded the app from F-droid and updated to latest version.

**Comment by PranavPurwar** [comment]
> > > Same here, with the latest build (1.5)
> > 
> > 
> > Which backend were you using?
> 
> Not gonna lie, I have no idea, I downloaded the app from F-droid and updated to latest version.

Just go to app settings, scroll down a bit and it'll show what's chosen as Primary Backend

**Comment by NovaXi** [comment]
> > > > Same here, with the latest build (1.5)
> > > 
> > > 
> > > Which backend were you using?
> > 
> > Not gonna lie, I have no idea, I downloaded the app from F-droid and updated to latest version.
> 
> Just go to app settings, scroll down a bit and it'll show what's chosen as Primary Backend

Oh yeah sorry, so I use Accessibility Services

**Comment by PranavPurwar** [comment]
> Oh yeah sorry, so I use Accessibility Services

Sorry, it was my bad for making the design confusing. You can change the backend to Usage Stats and it should be fixed. I'll see what I can do to fix the bug with accessibility service in the meanwhile.

**Comment by 66627392817293** [comment]
It seems that I do not have access to the backend settings. The section is just completely gone, therefore why I was confused. I didn't even know it was a thing.  I downloaded from F-froid. I have latest. Android 15, OneUi7. 

Maybe I messed up the setup ?

**Comment by PranavPurwar** [comment]
> It seems that I do not have access to the backend settings. The section is just completely gone, therefore why I was confused. I didn't even know it was a thing. I downloaded from F-froid. I have latest. Android 15, OneUi7.
> 
> Maybe I messed up the setup ?

Maybe you are using v1.3 Its only available from v1.4.1 onwards

**Comment by 66627392817293** [comment]
Well I updated the repos on Fdroid and it seems I only have access to V1.3. What gives ?

**Comment by PranavPurwar** [comment]
> Well I updated the repos on Fdroid and it seems I only have access to V1.3. What gives ?

There were some build problems on F-Droid. You can see #28 for more details.

**Comment by NovaXi** [comment]
> 
> > Oh yeah sorry, so I use Accessibility Services
> 
> Sorry, it was my bad for making the design confusing. You can change the backend to Usage Stats and it should be fixed. I'll see what I can do to fix the bug with accessibility service in the meanwhile.

Ok, no problem thank you!

**Comment by 66627392817293** [comment]
I installed latest throught github. 

Now it straight up doesn't work because Android thinks we're all babies and that accessibility settings is a machine gun or something. 

I'm creating a new issue, to find a way to circumvent yet another case of corporations trying to get a tight grip on my device, that I bought. 

I can't with these devs.

**Comment by PranavPurwar** [comment]
> I installed latest throught github.
> 
> Now it straight up doesn't work because Android thinks we're all babies and that accessibility settings is a machine gun or something.
> 
> I'm creating a new issue, to find a way to circumvent yet another case of corporations trying to get a tight grip on my device, that I bought.
> 
> I can't with these devs.

Install the new update directly through F-Droid or some other fdroid client. That would prevent the stupid "Restricted Setting" crap.

**Comment by Satanarious** [comment]
This issue still persists on Accessibility Services, Usage Statistics and Shizuku Services. I've tried using all 3 but the issue still persists, and I had to turn the app lock off to actually use the app.
